apiVersion: v1
kind: Service
metadata:
  name: argocd-example-app-service
spec:
  selector:
    app: argocd-example-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
    - port: 443
      protocol: TCP
      targetPort: 3000